### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ajansel** [wcsteve/swell#2]
# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
  - Make sure to add this for those that are not familiar with the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
  - This will likely be for workouts and routes
- [x] Estimates how long it will take the code each MVP
  - This still needs to be added. We can discuss this together this afternoon but for now maybe put your estimate and then we can update it when we meet.
- [x] Each App specific MVP needs the following bullet points are added:
  - The following three bullets above need to be included in the description for each issue that you make. They don't necessarily need to be on this MVP page though:
    + Adequate styling
    + Smooth, bug-free navigation
    + Seeded with info to demonstrate this feature

- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
      - Make sure to add at least one for each of the major 4 MVPs that provide more a description 

# Comments:
Looking great so far! Mainly small fixes / updates!

**Comment by wcsteve** [comment]
Updated

**Comment by ajansel** [comment]
Good to go, good work!
