### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ajansel** [wcsteve/swell#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
      - I would also make `icon_img_url` `not_null` for the reasons we discussed during flex time. 
    - [x] unique
      - Probably want the combination of `user_id` and `title` to be unique for both workouts and routes so they don't keep creating duplicates 
    - [x] indexed
      - You will need indices for the above mention under unique 
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - Great job with the associations, now just add which tables the foreign keys are referencing 
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
# Comments:
- We can talk more about `mapped_route` tomorrow in person, it's okay for now
- Great job so far!

**Comment by wcsteve** [comment]
Updated
