### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ajansel** [wcsteve/swell#4]
# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
  - You need `create` and `delete` for session
  - You need a user show page to return relevant user info 
  - You will also need `patch` requests for workouts and routes to complete the CRUD cycle
  - You will also need `create` for routes and workouts (workouts will probably be nested under routes)
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
  - When you say activity feed, do you mean dashboard of all their workouts? 
  - For routes and workouts, you don't need the :userId wildcard on the frontend
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
  - The HTML endpoint should be its own section
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
  - This needs updated (since it is Ruby)
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

# Comments:
Looking good!

**Comment by wcsteve** [comment]
"When you say activity feed, do you mean dashboard of all their workouts?" -> their is an activity logging each workout.  Similar to twitter/facebook feed.  There is also a workout stat page, which will be a "show" page for all workouts (stat page). There will be a link on the workouts page to create a workout.  
"You will also need create for routes and workouts (workouts will probably be nested under routes)" ->
-Im a little confused on this comment.  Workouts will be logged in a modal on the workouts stat page.

**Comment by ajansel** [comment]
Good to go!
