### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ajansel** [wcsteve/swell#5]
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
  - This needs updated
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `img_url` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with 3 back ticks before and after. This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
# Comments:
- Two small things: Change the second route id to `2`, add an `id` key-value pair to workouts
- I would name your image url in your state the same as it is in your database, right now they are different 
- Also, if a user has a certain set of workout and route ids they should be in the state. So I would add sample data for the current ids in the arrays for user 2 or change the arrays to only contain workouts / routes in the sample state
- This is great! Just change to camelCase

**Comment by wcsteve** [comment]
Updated

**Comment by ajansel** [comment]
Good to go, nicely done!
